version: "3"

services:

    shortener_server:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: shortener_image
        container_name: shortener_server
        restart: unless-stopped
        env_file:
            - ./backend/.env.example
        ports:
            - "8000:8000"
        depends_on:
            - postgres_server
            - test_postgres_server
            - redis_server

    postgres_server:
        image: postgres:13
        container_name: postgres_shortener
        restart: unless-stopped
        volumes:
            - ./backend/databases/postgres/data:/var/lib/postgresql/data/
        env_file:
            - ./backend/.env.example
        expose:
            - 5432

    test_postgres_server:
        image: postgres:13
        container_name: test_postgres_shortener
        restart: unless-stopped
        env_file:
            - ./backend/.env.example
        environment:
            - POSTGRES_SERVER=${TEST_POSTGRES_SERVER}
            - POSTGRES_DB=${TEST_POSTGRES_DB}
        expose:
            - 5432

    redis_server:
        image: redis
        container_name: redis_shortener
        restart: unless-stopped
        volumes:
            - ./backend/databases/redis/data:/data
            - ./backend/databases/redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - ${REDIS_PORT}
        command: redis-server /usr/local/etc/redis/redis.conf
        

